<?php
/**
 * @file
 *
 */
/**
 * Implements hook_menu()
 */
function useradmin_menu() {
  $items = array();
  $items['useradmin/create_new_user'] = array(
    'title' => 'Create New User',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('useradmin_create_user_form'),
    'access arguments' => array('view site internal content'),
    'type' => MENU_CALLBACK,
    'file' => 'useradmin_create_user_form_page.inc',
  );
  $items['useradmin/new_user'] = array(
    'title' => 'Create New User',
    'page callback' => 'useradmin_new_user',
    'access arguments' => array('view site internal content'),
    'type' => MENU_CALLBACK,
    'file' => 'useradmin_create_user_form_page.inc',
  );
  return $items;
}