<?php
/**
 * @file
 *
 */

/*
 * Implementation of hook_init()
 */

/**
 * Implements hook_menu()
 */
function clientterm_menu() {
  $items = array();

  $items['clientterm/add_new'] = array(
    'title' => 'Client Term Default Title',
    'page callback' => 'clientterm_add_new_term_form',
    'access arguments' => array('view site internal content'),
    'type' => MENU_CALLBACK,
    'file' => 'clientterm_add_new_form_page.inc',
  );

  $items['clientterm/pp_user'] = array(
    'title' => 'Client Term cc Title',
    'page callback' => 'clientterm_form_load_user',
    // 'access arguments' => TRUE,
    'access arguments' => array('view site internal content'),
    'file' => 'clientterm_form_load_page.inc',
  );

  $items['clientterm/pp_term'] = array(
    'title' => 'Client Term cc Title',
    'page callback' => 'clientterm_form_load_term',
    // 'access arguments' => TRUE,
    'access arguments' => array('view site internal content'),
    'file' => 'clientterm_form_load_page.inc',
  );


  $items['clientterm/pp_vocabulary'] = array(
    'title' => 'Client Term cc Title',
    'page callback' => 'clientterm_form_load_term',
    // 'access arguments' => TRUE,
    'access arguments' => array('view site internal content'),
    'file' => 'clientterm_form_load_page.inc',
  );

  return $items;
}

/**
 * hook_form_alter()
 * hide title field, and assign a default title
 */
function clientterm_form_alter(&$form, &$form_state, $form_id) {
dpm($form_id);
  if ($form_id == 'taxonomy_form_term') {
    if ($form_state['term']->vocabulary_machine_name == 'client') {
    }
  }
}