<?php
/**
 * @file
 */

/**
 * class
 */
class OtherNotifyMail {
  public $tid;
  public $term = NULL;

  /**
   * @parameter is tid
   */
  function __construct(){

  }

  /**
   * call from hook_cron()
   *
   * @to call different term with time validate
   */
  public function checkTermNotify() {

  }

  /**
   * call from hook_cron()
   *
   * @to call different term with time validate
   */
  public function checkTermNotify() {

  }


}