<?php
/**
 * @file
 *
 */
/**
 * Implements hook_menu()
 */
function searchpage_menu() {
  $items = array();
  $items['searchpage'] = array(
    'title' => 'Search Repair Item',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('othersetting_set_quote_value_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'othersetting_set_quote_value_form_page.inc',
  );
  return $items;
}