<?php
/**
 * @file
 *
 */

/**
 * Implements hook_menu()
 */
function othersetting_menu() {
  $items = array();

  $items['othersetting/set_quote_value'] = array(
    'title' => 'Quote Default Value',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('othersetting_set_quote_value_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'othersetting_set_quote_value_form_page.inc',
  );

  return $items;
}

/**
 * @return
 * default Quotation page text content
 */
function othersetting_quote_page_content($node = NULL) {
  $device_name = '';
  if (isset($node)){
    foreach ($node->field_quote_repair_nid['und'] as $key => $row) {
      if (!empty($row['value'])){
        $repair_node = node_load($row['value']);
        if (isset($repair_node)){
        $device_term = taxonomy_term_load($repair_node->field_repair_1st_devicetype['und'][0]['tid']);
        $device_name .= $device_term->name . '<br />';
        }
      }
    }
  }
  // $device_content = $node->field_quote_repair_nid['und'][0]['value'];


  $output = '';
  $output =  t('产品保修期外维修单') . '<br />'
               . t('贵公司送修的解码器')
               . t('型号:') . '<br />'
               . '<p><span class="quotation_insert_markup_device_type">'
               . ((isset($node)) ? $device_name : '')
               . '</span></p>'
               . t('已经超过保修期, 需要更换配件, 维修后仅对该设备配件将提供为期')
               . '<span class="quotation_insert_markup_warranty_day">'
               . ((isset($node)) ? $node->field_quote_warranty_day['und'][0]['value'] : variable_get('quote_default_value_warranty_day'))
               . '</span>'
               . t('天的保修服务。')
               . '<br />'
               . t('维修情况如下：')
               . '<div class="col-xs-11 quote-row-output-html color-449bb5">'
               . '</div>'
               . '<div class="clear-both"></div>'
               . t('因已经超过保修期，需要支付维修费.费用为') . '￥'
               . '<span class="quotation-insert-markup-sum-price">'
               . ((isset($node)) ? $node->field_quote_sum_price['und'][0]['value'] : '')
               . '</span>'
               . '(' . t('人民币')
               . '<span class="quotation-insert-markup-chinese-price">'
               . ((isset($node)) ? num2rmb($node->field_quote_sum_price['und'][0]['value']) : '')
               . '</span>'
               . t('元整') . ').' . t('维修后该设备相同部件将提供为期')
               . '<span class="quotation_insert_markup_warranty_day">'
               . ((isset($node)) ? $node->field_quote_warranty_day['und'][0]['value'] : variable_get('quote_default_value_warranty_day'))
               . '</span>'
               . t('天的保修服务.')
               . '<br />'
               . '<div class="clear-both"></div>'
               . t('以下是我司有关汇款信息：') . '<br /><br />'
               . t('名称：')
               . '<span class="quotation_insert_markup_company_name">'
               . ((isset($node)) ? $node->field_quote_company_name['und'][0]['value'] : variable_get('quote_default_value_company_name'))
               . '</span>'
               . '<br />'
               . t('开户行：交通银行北京水碓子支行') . '<br />'
               . t('帐号：110060970018010024476')
               . '<br /><br />'
               . t('收到维修费后，')
               . '<span class="quotation_insert_markup_company_name">'
               . ((isset($node)) ? $node->field_quote_company_name['und'][0]['value'] : variable_get('quote_default_value_company_name'))
               . '</span>'
               . t('负责开具发票，并将设备快递回贵公司。') . '<br />'
               . t('李靖') . '<br />'
               . '<span class="quotation_insert_markup_create_date">'
               . ((isset($node)) ? date('Y-m-d', $node->field_quote_create_date['und'][0]['value']) : date('Y-m-d'))
               . '</span>';

  return $output;
}

/**
 * 人民币小写转大写
 *
 * @param string $number 数值
 * @param string $int_unit 币种单位，默认"元"，有的需求可能为"圆"
 * @param bool $is_round 是否对小数进行四舍五入
 * @param bool $is_extra_zero 是否对整数部分以0结尾，小数存在的数字附加0,比如1960.30，
 *             有的系统要求输出"壹仟玖佰陆拾元零叁角"，实际上"壹仟玖佰陆拾元叁角"也是对的
 * @return string
 * http://ustb80.blog.51cto.com/6139482/1035327
 */
function num2rmb($number = 0, $int_unit = '元', $is_round = TRUE, $is_extra_zero = FALSE) {
  // 将数字切分成两段
  $parts = explode('.', $number, 2);
  $int = isset($parts[0]) ? strval($parts[0]) : '0';
  $dec = isset($parts[1]) ? strval($parts[1]) : '';

  // 如果小数点后多于2位，不四舍五入就直接截，否则就处理
  $dec_len = strlen($dec);
  if (isset($parts[1]) && $dec_len > 2) {
    $dec = $is_round
            ? substr(strrchr(strval(round(floatval("0.".$dec), 2)), '.'), 1)
            : substr($parts[1], 0, 2);
  }

  // 当number为0.001时，小数点后的金额为0元
  if(empty($int) && empty($dec)) {
    return '零';
  }

  // 定义
  $chs = array('0','壹','贰','叁','肆','伍','陆','柒','捌','玖');
  $uni = array('','拾','佰','仟');
  $dec_uni = array('角', '分');
  $exp = array('', '万');
  $res = '';

  // 整数部分从右向左找
  for($i = strlen($int) - 1, $k = 0; $i >= 0; $k++) {
    $str = '';
    // 按照中文读写习惯，每4个字为一段进行转化，i一直在减
    for($j = 0; $j < 4 && $i >= 0; $j++, $i--)
    {
        $u = $int{$i} > 0 ? $uni[$j] : ''; // 非0的数字后面添加单位
        $str = $chs[$int{$i}] . $u . $str;
    }
    //echo $str."|".($k - 2)."<br>";
    $str = rtrim($str, '0');// 去掉末尾的0
    $str = preg_replace("/0+/", "零", $str); // 替换多个连续的0
    if(!isset($exp[$k]))
    {
        $exp[$k] = $exp[$k - 2] . '亿'; // 构建单位
    }
    $u2 = $str != '' ? $exp[$k] : '';
    $res = $str . $u2 . $res;
  }

  // 如果小数部分处理完之后是00，需要处理下
  $dec = rtrim($dec, '0');

  // 小数部分从左向右找
  if(!empty($dec)) {
    $res .= $int_unit;

    // 是否要在整数部分以0结尾的数字后附加0，有的系统有这要求
    if ($is_extra_zero) {
      if (substr($int, -1) === '0') {
        $res.= '零';
      }
    }

    for($i = 0, $cnt = strlen($dec); $i < $cnt; $i++) {
      $u = $dec{$i} > 0 ? $dec_uni[$i] : ''; // 非0的数字后面添加单位
      $res .= $chs[$dec{$i}] . $u;
    }
    $res = rtrim($res, '0');// 去掉末尾的0
    $res = preg_replace("/0+/", "零", $res); // 替换多个连续的0
  }
  else {
    $res .= $int_unit . '整';
  }
  return $res;
}