<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init()
 */
function quotetype_init() {
  // add ajax function for form page.
  module_load_include('inc', 'quotetype', 'quotetype_page_form_ajax');
  module_load_include('inc', 'quotetype', 'quotetype_ajax_stamp_block_form');
}

/**
 * Implements hook_block_info().
 */
function quotetype_block_info() {
  $blocks = array();
  $blocks['quotetype_ajax_stamp'] = array(
    'info' => t('quotetype AJAX Stamp Block'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function quotetype_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'quotetype_ajax_stamp':
      // $block['subject'] = 'AJAX Stamp for Quote';
      $block['content'] = drupal_get_form('quotetype_ajax_stamp_block_form');
      break;
  }
  return $block;
}

/**
 * Implements hook_menu()
 */
function quotetype_menu() {
  $items = array();
  $items['add_new_quotation'] = array(
    'title' => 'Create New Quotation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('quotetype_add_quote_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'quotetype_page_form.inc',
  );
  return $items;
}

/**
 * hook_form_alter()
 * hide title field, and assign a default title
 */
function quotetype_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'quote_node_form') {
    // adjust node title
    $form['title']['#default_value'] = t('Quotation');
    // $form['title']['#type'] = 'hidden';
    // $form['title']['#required'] = FALSE;
  }
}

/**
 * @return
 * Authorize Stamp image
 * @parameter 1 is width of image size, default is 128px
 * @parameter 2 is height of image size, default is 128px
 */
function quotetype_authorize_stamp_image($width = '64px', $height = '28px') {
  $stamp_image_path = '/' . drupal_get_path('module', 'quotetype') . '/images/wanbo_quote_stamp.png';
  $stamp_image_variables = array(
                            'path' => $stamp_image_path,
                            'alt' => 'Stamp',
                            'title' => 'Stamp',
                            'width' => $width,
                            'height' => $height,
                           );
  $stamp_image = theme('image', $stamp_image_variables);
  return $stamp_image;
}