<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init()
 */
function quotetype_init() {
  // add ajax function for form page.
  module_load_include('inc', 'quotetype', 'quotetype_page_form_ajax');
}

/**
 * Implements hook_menu()
 */
function quotetype_menu() {
  $items = array();

  $items['add_new_quotation'] = array(
    'title' => 'Create New Quotation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('quotetype_add_quote_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'quotetype_page_form.inc',
  );
  
  $items['quote/get/ajax/%'] = array(
    'page callback' => 'myModule_ajax_get_ajax', // Render HTML
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'myModule_ajax_callback',  // Magic goes here
  );

  return $items;
}

function myModule_ajax_get_ajax($nid) {
  // Just load a node and return teaser, you can return whatever you want including forms
  $node = node_load($nid);
  return node_view($node, 'full');
}

function myModule_ajax_callback($page_callback_result) {
  // Only render content
  $content = drupal_render($page_callback_result);
  
  // Add CSS ans JS files, add some markup
  $html = '<html><head><title></title>' . drupal_get_css() . drupal_get_js() . '</head><body class="jquery-ajax-load">' . $content . '</body></html>';
  print $html;

  // Perform end-of-request tasks.
  drupal_page_footer();
}

/**
 * hook_form_alter()
 * hide title field, and assign a default title
 */
function quotetype_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'quote_node_form') {
    // adjust node title
    $form['title']['#default_value'] = t('Quotation');
    // $form['title']['#type'] = 'hidden';
    // $form['title']['#required'] = FALSE;
  }
}